/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './_includes/**/*.liquid',
    './_layouts/**/*.liquid',
    './_sections/**/*.liquid',
    './pages/**/*.liquid',
    './pages/**/*.html',
    './*.liquid',
    './*.html',
  ],
  theme: {
    extend: {
      colors: {
        midnight: {
          DEFAULT: '#0A0B1E',
          light: '#1A1B3A',
          medium: '#2D2F5E',
        },
        cloud: {
          DEFAULT: '#F7F7FA',
          dark: '#E8E8F0',
        },
        gold: {
          DEFAULT: '#D4AF37',
          light: '#E4C65A',
          dark: '#B8952E',
        },
      },
      fontFamily: {
        display: ['"Playfair Display"', 'Georgia', 'serif'],
        body: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['4.5rem', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
        'display-lg': ['3.5rem', { lineHeight: '1.15', letterSpacing: '-0.02em' }],
        'display': ['2.75rem', { lineHeight: '1.2', letterSpacing: '-0.015em' }],
        'heading-xl': ['2.25rem', { lineHeight: '1.25', letterSpacing: '-0.01em' }],
        'heading-lg': ['1.75rem', { lineHeight: '1.3', letterSpacing: '-0.01em' }],
        'heading': ['1.375rem', { lineHeight: '1.35', letterSpacing: '-0.005em' }],
        'body-lg': ['1.125rem', { lineHeight: '1.7' }],
        'body': ['1rem', { lineHeight: '1.7' }],
        'body-sm': ['0.875rem', { lineHeight: '1.6' }],
        'caption': ['0.75rem', { lineHeight: '1.5' }],
      },
      spacing: {
        '0.5': '0.125rem',
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '8': '2rem',
        '10': '2.5rem',
        '12': '3rem',
        '16': '4rem',
        '20': '5rem',
        '24': '6rem',
        '32': '8rem',
        '40': '10rem',
        '48': '12rem',
        '56': '14rem',
        '64': '16rem',
      },
      borderRadius: {
        'sm': '6px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        '2xl': '24px',
        'full': '9999px',
      },
      boxShadow: {
        'soft': '0 2px 16px rgba(10, 11, 30, 0.06), 0 1px 4px rgba(10, 11, 30, 0.04)',
        'elevated': '0 8px 32px rgba(10, 11, 30, 0.08), 0 2px 8px rgba(10, 11, 30, 0.04)',
        'deep': '0 16px 48px rgba(10, 11, 30, 0.12), 0 4px 16px rgba(10, 11, 30, 0.06)',
        'gold': '0 4px 24px rgba(212, 175, 55, 0.25)',
        'btn': '0 2px 8px rgba(10, 11, 30, 0.12)',
        'btn-hover': '0 4px 16px rgba(10, 11, 30, 0.16)',
      },
      animation: {
        'fade-in': 'fadeIn 0.6s ease-out',
        'fade-up': 'fadeUp 0.8s ease-out',
        'slide-in': 'slideIn 0.4s ease-out',
        'scale-in': 'scaleIn 0.3s ease-out',
        'spin-slow': 'spin 3s linear infinite',
        'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideIn: {
          '0%': { opacity: '0', transform: 'translateX(-16px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
      },
      screens: {
        'xs': '480px',
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1440px',
        '3xl': '1600px',
      },
      maxWidth: {
        'page': '1440px',
        'content': '1200px',
        'narrow': '800px',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'hero-gradient': 'linear-gradient(135deg, #0A0B1E 0%, #1A1B3A 50%, #2D2F5E 100%)',
        'section-gradient': 'linear-gradient(180deg, #F7F7FA 0%, #E8E8F0 100%)',
        'gold-gradient': 'linear-gradient(135deg, #D4AF37 0%, #E4C65A 50%, #B8952E 100%)',
      },
    },
  },
  plugins: [],
};
